sudo: false
language: cpp
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake ..
  - make
  - g++ client_LR6.c -o client_LR6
  - ./test
  - ./client_LR6 3324
